### ISSUE TITLE
Change AddTransient to TryAddTransient?

### ISSUE THREAD

**Issue by thisispaulsmith** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#10]
Calling...

```
services.AddMediatR()
```

..overwrites any mediators that may have been previously added in say a `TestServer` since adding any mocked services is called before `Startup.ConfigureServices()`

Could `AddTransient()` be switched to `TryAddTransient`?

**Comment by jbogard** [comment]
What's being mocked exactly?

**Comment by thisispaulsmith** [comment]
Running some basic unit/integration tests against some API controllers, routes, permissions, response codes etc. I'm not bothered about the specifics of the mediators and their dependencies so I want to add dummy mediators.

**Comment by jbogard** [comment]
Hmmmm....do you have a more complete example? I'm interested in the mocking side of things myself.

**Comment by thisispaulsmith** [comment]
I have create a very crude example
https://github.com/thisispaulsmith/NetCoreMediatr

The test doesn't test anything specific but it shoes how you could.

**Comment by jbogard** [comment]
Gotcha, thanks!
