### ISSUE TITLE
Allow other lifecycles for handlers than transient

### ISSUE THREAD

**Issue by geoffroybraun** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#110]
Hi,

as I understood from both the wiki and my use of 'MediatR' NuGet package, all handlers are registered within the services collection as 'transient'. I believe it would be nice to have this behavior by default but also the opportunity to choose the lifecycle of all handlers of an assembly without having to implement the 'IMediatR' interface ourselves. So far, we have to create injectable classes with let us say a 'scoped' lifecycle so they can be used within handlers, but this forces us to adapt our code to the package.

Please let me know if you misunderstood something to have 'scoped' handlers instead of 'transient'. Otherwise, I believe this update would be incredibly useful for all users.

Thanks,

Geoffroy

**Comment by jbogard** [comment]
You don't need scoped handlers to have scoped dependencies inside a handler. The only problematic one is Singleton depending on transient/scoped. See: https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#service-lifetimes

**Comment by geoffroybraun** [comment]
First thing first, thanks a lot for the reply and the link, it's always good to read something like this even though I already had. 

What I was thinking is more like not having to create the scoped dependency to inject within the handler. In my case, I have to call a handler multiple times, and some data have to be stored within the instance call after call, like in a dictionary or something. But as I said, the handler is transient, so I can't store anything in it, forcing me to create a dedicated service with a 'scoped' lifecycle to have it injected within the handler. This way, I am able to call a handler mutiple times while storing data in-memory, as they are stored within the dedicated service, but I had to create this service because the handler is transiet. Otherwise, I'd done this within the handler, without any injected service.

Does this make more sense ?

Thanks a lot,

Geoffroy

**Comment by jbogard** [comment]
Yes and

don't store data in your handler. Absolutely create a dependency that is managing that state. Then you can name that type appropriately. Handlers should be stateless and delegate to other services that "cache" or whatever.

**Comment by geoffroybraun** [comment]
Alright, I understand the philosophy of it. Handlers should remain stateless, all the rest depends on my application.

Again, thanks for the reply, I'll close the issue then.
