### ISSUE TITLE
Error when registering dbcontext implementation

### ISSUE THREAD

**Issue by raminmjj** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#112]
Hi,
I created an application based on the "[Clean Architecture Solution Template](https://github.com/jasontaylordev/CleanArchitecture)".
and add another database provider like this [article](https://jasonwatmore.com/post/2020/01/03/aspnet-core-ef-core-migrations-for-multiple-databases-sqlite-and-sql-server?utm_source=pocket_mylist).
everything works fine when the provider is set to base dbcontext, but when I change provider to another,  I got these errors:
![image](https://user-images.githubusercontent.com/991847/148056775-e592bce7-1e72-4d21-8094-f73b174c6e88.png)
----
![image](https://user-images.githubusercontent.com/991847/148056803-db3ac871-dc66-4827-be78-552c5d2173ba.png)

the second dbcontext registration is like this:
![image](https://user-images.githubusercontent.com/991847/148056939-d957e68c-a674-4ee5-9d30-e910265a2772.png)

Thank you.

**Comment by jbogard** [comment]
This is not an issue with MediatR or how MediatR is registered with the container. You're trying to use a scoped service (DbContext) outside of a scope. You need to create a scope, then resolve services from that scope. See [this example](https://docs.microsoft.com/en-us/dotnet/core/extensions/scoped-service).

**Comment by raminmjj** [comment]
Hi, jimmy.
you're right, the problem was in the base dbcontext constructor. 
I changed it from:
![image](https://user-images.githubusercontent.com/991847/148672668-79e5efa8-62ea-4d13-8cf6-e4ea237737ea.png)

to

![image](https://user-images.githubusercontent.com/991847/148672683-3a8d3302-7629-4cdf-b80f-728fc91da1a7.png)

Thank you.
