### ISSUE TITLE
InvalidOperationException: Cannot resolve 'MediatR.IRequestHandler' from root provider because it requires scoped service dbContext

### ISSUE THREAD

**Issue by rezabashiri** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#113]
I was reading and checking all solutions to this exception but could manage to resolve that, All services and repositories have been injected correctly and I can handler explicitly without going through MediatR

Startup.cs is 
`   services.AddInfrastructureServices(this.Configuration);
            services.AddCoreServices();
            services.AddControllers();
services.AddMediatR(Assembly.GetExecutingAssembly());`
and 
` public static void AddInfrastructureServices(this IServiceCollection services, IConfiguration configuration)
        {
            services.AddDbContext<DataContext>(options =>
           {
               options.UseSqlServer(configuration.GetConnectionString("WfEngineContext"));
           });
            services.AddDbContext<AramestanDataContext>(options =>
            {
                options.UseSqlServer(configuration.GetConnectionString("AramestanContext"));
            }); }`

Using MediatR 9 to handle requests, and another code like this in another project of mine is working correctly

**Comment by jbogard** [comment]
See #112
