### ISSUE TITLE
Extending handlers works if the handler only implements IRequestHandler once

### ISSUE THREAD

**Issue by fepettersen** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#116]
Came across some weird behavior that I think is unintentional. The minimal example is that I have a RequestHandler that is extended in a test-project in order to override some functionality. I have a workaround for this, but I still think this should be reported.

My RequestHandler looks like this (Adding the Requests and Mediator implementation as well):
```
public class QueryHandler : IRequestHandler<Query1, string>
                //, IRequestHandler<Query2, string>
{
    public Task<string> Handle(Query1 request, CancellationToken cancellationToken) => 
        Task.FromResult(DoSomething());
    public Task<string> Handle(Query2 request, CancellationToken cancellationToken) =>
            Task.FromResult(DoSomething());

    public virtual string DoSomething() => nameof(QueryHandler);
}
public class DemoMediator : Mediator
{
    public DemoMediator(ServiceFactory serviceFactory) : base(serviceFactory)
    {
    }
}

public class Query1 : IRequest<string> { }
public class Query2 : IRequest<string> { }
```
And My Test looks like this (adding the override-class)
```
public class UnitTests
{
    [Fact]
    public void Test1()
    {
        GetMediator();
        Assert.True(true);
    }

    public static IMediator GetMediator() =>
        new ServiceCollection()
            .AddLogging()
            .AddMediatR(configuration =>
            {
                configuration.Using<DemoMediator>();
            }, AppDomain.CurrentDomain.GetAssemblies())
            .BuildServiceProvider()
            .GetRequiredService<IMediator>();
}
public class QueryHandlerOverride : QueryHandler
{
    public override string DoSomething() => nameof(QueryHandlerOverride);
}
```
**As it stands now, the test passes. When this line is commented in `//, IRequestHandler<Query2, string>` the test fails.** 

I'm having some trouble determining if both cases should pass or not: A request should only have one handler, but the wiki hints that overrides should be possible (https://github.com/jbogard/MediatR/wiki#override-handleraction). However, I am certain that they should behave in the same way.

**Comment by jbogard** [comment]
This isn't a supported scenario for this library but I'm open to a PR to add support.

**Comment by fepettersen** [comment]
Okay, I'll see if I can get the time.
