### ISSUE TITLE
DI using types doesn't seem to work as intented

### ISSUE THREAD

**Issue by rainier-bacareza** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#122]
Hi,

So we have a console application that is dependent on 2 Projects, these 2 projects contains Handlers that we wanted to be injected but not all, and some comes from console app. However when we tried to inject the handler (types) inside the Console App, the DI seems to scan every handler in its dependent causing a unresolvable dependencies. 

We have fixed the issue by using "WithEvaluator" method. Below is our sample code.

![image](https://user-images.githubusercontent.com/84911268/175462286-f85dc6ad-6afd-4be1-9079-9601ae83d58e.png)

**Comment by jbogard** [comment]
It's not "seems to", that's exactly the point of this library. If you only want specific handlers to be registered, I wouldn't use this library at all. Just manually register your types so you don't have the assembly scanning.
