### ISSUE TITLE
Need version upgrade for Microsoft.Extension.DependencyInjection.Abstractions in the package

### ISSUE THREAD

**Issue by SyedObaidGit** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#124]
I am using Microsoft.Extensions.Http which is using Microsoft.Extension.DependencyInjection.Abstractions >= (7.0.0). But the package is using Microsoft.Extension.DependencyInjection.Abstractions >= (6.0.0). 
I am getting an error because of version conflict. I have to down grade the Microsoft.Extensions.Http package to work with the package
Can you upgrade the version.

**Comment by jbogard** [comment]
You don't have to downgrade, you just need to explicitly add a package reference to 7.0.
