### ISSUE TITLE
AsyncNotificationHandlers dosn't fire after publish asp.net core app on remote server

### ISSUE THREAD

**Issue by araxis** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#17]

**Comment by jbogard** [comment]
Do you have any more information?

**Comment by jbogard** [comment]
Odd it all works locally but not when deployed? And only the notification handlers?

**Comment by araxis** [comment]
yes

**Comment by araxis** [comment]
it is my fault.your library work perfectly.
i am so sorry.

**Comment by jbogard** [comment]
No problem! What was the issue?

**Comment by araxis** [comment]
in fact notification handler executed,but because of a wrong config my db connection throw an exception that not handled.
