### ISSUE TITLE
Internal scoped handlers are not found

### ISSUE THREAD

**Issue by vdecristofaro** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#18]
If an handler is declared with the `internal` visibility scope it does not get registered by the library.

example

`internal class AccountListHandler : IRequestHandler<AccountListRequest, Result<IEnumerable<AccountResult>>>`

Also one more question. Does this package helps registering also `IRequestPreProcessor`, `IRequestPostProcessor` and `IPipelineBehavior` types?

**Comment by jbogard** [comment]
I'll take a PR for the first one.

And for the second one, no you have to register them explicitly. I should add something to the readme for that :)

**Comment by vdecristofaro** [comment]
:ok_hand: I'll try to give it a try as soon as I can work on it.
