### ISSUE TITLE
Asp.Net Core always returns the same instance for scoped services

### ISSUE THREAD

**Issue by brunoalbano** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#2]
The Asp.Net Core is resolving scoped dependencies of a handler as singleton. I created a [test to demonstrate the problem](https://github.com/brunoalbano/MediatR.Extensions.Microsoft.DependencyInjection/blob/master/test/MediatR.Extensions.Microsoft.DependencyInjection.Tests/AspNetTests.cs).

The SimpleInjector faced a similar [issue](https://github.com/simpleinjector/SimpleInjector/issues/261).

I was able to fix this in my project by adding this code:
```c#
services.AddMediatR(typeof(Startup));
services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
services.AddScoped<SingleInstanceFactory>(p =>
{
    return t =>
    {
        var httpContextAccessor = p.GetRequiredService(typeof(IHttpContextAccessor)) as IHttpContextAccessor;
        return httpContextAccessor.HttpContext.RequestServices.GetRequiredService(t);
    };
});
```

**Comment by henkmollema** [comment]
I assume this is fixed by using a scoped lifetime for the Mediator: 12f519b9f94c92b1d8c8a50b0eaa67894224a7f3.

**Comment by jbogard** [comment]
yes! it is.

**Comment by jbogard** [comment]
Basically the .NET Core DI container doesn't work like others do w.r.t. scoped lifetimes.

**Comment by henkmollema** [comment]
Yep, I've been bitten by the issue with a singleton `Mediator` too:

**Comment by jbogard** [comment]
The latest extension treats Mediator as a scoped dependency. That seemed to fix all.

There's really no reason for the Mediator dependency to be a singleton anyway tho.

**Comment by henkmollema** [comment]
Yes, scoped dependency is fine 👍

**Comment by brunoalbano** [comment]
Perfect, Thank you!
