### ISSUE TITLE
ASP.NET CORE Unable to resolve IMediator from IHostedService

### ISSUE THREAD

**Issue by aownshah** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#20]
I have a back ground Service which implement IHostedService. I am using mediatr in it to send commends and notification to different objects from this hosted service. 

public class Startup
{
........
     public void ConfigureServices(IServiceCollection services)
     {
      ........
      services.AddMediatR(typeof(Startup).GetTypeInfo().Assembly);
      .....
      

On runtime, i get this error:
System.InvalidOperationException: 'Cannot consume scoped service 'MediatR.IMediator' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.'

**Comment by jbogard** [comment]
You need to create a scope first. Then you can run the Mediator, this is by design.
