### ISSUE TITLE
It's a shame that AddRequiredServices isn't public via some means.

### ISSUE THREAD

**Issue by rustybox** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#22]
I am assembly scanning and registering all classes as implemented interfaces and ended up with notification handlers running twice.

My hotfix for now is to not use these extensions, but it'd be nice to have it for the boilerplate just without scanning for notifcation/request handlers.

**Comment by jbogard** [comment]
It's not really designed to be used partially. Is there something else that would make sense so that handlers aren't added twice?

**Comment by rustybox** [comment]
How about an optional skip flag on the call to services.AddMediatr ?

**Comment by jbogard** [comment]
So is this a bug that notification handlers are running twice then?

**Comment by rustybox** [comment]
I wouldn't say it's a bug.

This extension registers all found notification handlers, It just happens that the handler lives in an assembly for which I am registering all classes as implemented interfaces, so my container ends up with two registrations for INotificationHandler<T>

So as a user I have option

1. I could move all NotificationHandler implementations out to a different assembly which gets scanned by this extension and not by my catch all registration.
2. I could exclude the namespace that contains my notification handlers when registering all classes as implemented interfaces.
3. Skip usage of this extension so I have more control over registration but then I have to write all the blurb to add mediator to my container along with RequestHandlers.
4. ideally from my perspective have a flag that stops this extension from registering NotificationHandlers
```c#
     services.AddMediatR(typeof(Startup).GetTypeInfo().Assembly, skipHandlerRegistrations: true);
```
