### ISSUE TITLE
Can't register PreProcessor

### ISSUE THREAD

**Issue by MrSmoke** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#25]
Not sure if I'm doing something wrong here, but I have a Pre Processor defined as:

```cs
public class RunPreProcessor : IRequestPreProcessor<EndRunCommand>
```

which throws the following error when calling `.AddMediatR()`:

> Open generic service type 'MediatR.Pipeline.IRequestPreProcessor`1[TRequest]' requires registering an open generic implementation type.'

If I comment out the class, the DI doesn't throw any errors. Registering manually works fine if I comment out `.AddMediatR()`

```cs
services.AddTransient<IRequestPreProcessor<EndRunCommand>, RunPreProcessor>();
```

If I register before `.AddMediatR()` it doesn't seem to skip already registered PreProcessors?

Changing to a generic handler seems to fix is. Is that the recommended approach?

```cs
public class RunPreProcessor<TCommand> : IRequestPreProcessor<TCommand>
{
    public Task Process(TCommand request, CancellationToken cancellationToken)
    {
        if (request is EndRunCommand command)
            return Process(command, cancellationToken);

        return Task.CompletedTask;
    }
}
```

**Comment by MrSmoke** [comment]
Glad to know 2am me wasn't crazy 😄

**Comment by maldworth** [comment]
👍 I just encountered this. Will use the Generic workaround, but I hope this will be fixed.

**Comment by steveoh** [comment]
Just bumped into this also.

**Comment by steveoh** [comment]
I'm going to try to fix this. Any help would be appreciated because I think it's a bit out of my experience.

**Comment by steveoh** [comment]
Ok, I give up. I'm not sure what I'm doing. Sorry folks.
