### ISSUE TITLE
In ASP.Net Core 1.0 project, notification is handled twice in handler

### ISSUE THREAD

**Issue by mgmccarthy** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#3]
this duplicate handling was causing the same email to be sent twice to the same person...

I fixed it in our project removing the `MediatR.Extensions.Microsoft.DependencyInjection` package and reverting to the old way of registering MediatR... basically, something like this:

```
var containerBuilder = new ContainerBuilder();
containerBuilder.RegisterSource(new ContravariantRegistrationSource());
containerBuilder.RegisterAssemblyTypes(typeof(IMediator).Assembly).AsImplementedInterfaces();
containerBuilder.RegisterAssemblyTypes(typeof(Startup).Assembly).AsImplementedInterfaces();
containerBuilder.Register<SingleInstanceFactory>(ctx =>
{
    var c = ctx.Resolve<IComponentContext>();
    return t => c.Resolve(t);
});

containerBuilder.Register<MultiInstanceFactory>(ctx =>
{
    var c = ctx.Resolve<IComponentContext>();
    return t => (IEnumerable<object>)c.Resolve(typeof(IEnumerable<>).MakeGenericType(t));
});
```

How can I provide you more information to see if this is a bug or we're not using/registering MediatR correctly?

**Comment by jbogard** [comment]
A small repro would help, can you try to isolate it to a generic usage?

**Comment by EwoutdBoer** [comment]
Jimmy,
I do have the same problem. See my pull request with a test that reproduces the problem.
Regards Ewout
