### ISSUE TITLE
AddMediatR() not finding handlers in referenced libraries

### ISSUE THREAD

**Issue by Artem-Romanenia** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#38]
In my asp.net core project, my handlers are located in a library that is referenced by main project. At the point where parameterless AddMediatR is called, this library is not loaded to AppDomain yet, so AddMediatR() cannot register those handlers.

Is this by design and I should specify explicitly the assemblies where handlers are located?

**Comment by jbogard** [comment]
Yes, it is. If the assemblies aren’t loaded yet, you’ll need to specify
them. I have no way of finding hem otherwise.

**Comment by Artem-Romanenia** [comment]
Got it! Thank you for your reply!

I think of playing around with a fork of this repo, and trying to do something similar to what asp.net core does in ApplicationPartManager and ApplicationAssembliesProvider to discover assemblies that have controllers in them. The major difference would be that aspnet searches for assemblies referencing major Mvc projects, whereas here it can search for assemblies referencing Mediatr.

So, if I ever come up with some decent solution, would you consider accepting a pull request?

**Comment by jbogard** [comment]
So it used to do what that did, but the code was horrible. At this point
I’d rather just force you to tell me where to look.

**Comment by Artem-Romanenia** [comment]
I see, thanks again for your time!
