### ISSUE TITLE
Add ability to specify custom IMediator implementation

### ISSUE THREAD

**Issue by thiagolunardi** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#42]
I wrote my custom `IMediator` implementation, and now I'd like to keep using  `MediatR.Extensions.Microsoft.DependencyInjection` but specifying my custom implementation.

Something like 
```
services.AddMediatR().Using<MyCustomMediator>();
```
Or even:
```
services.AddMediatR(cfg => cfg.Using<MyCustomMediator>());
```
By that, I will keep having all benefits of `MediatR.Extensions.Microsoft.DependencyInjection`, plus flexibility.

**Comment by jbogard** [comment]
What does this class do?

**Comment by jbogard** [comment]
But what does your class provide that the built in one does not?

**Comment by thiagolunardi** [comment]
Well, as the first moment, it doesn't matter. But just for context, I created my own implementation for sake of testings.
 
The `IMediator` is a public interface, which means I can have my own implementation of it and will be really nice if I can use the same extension to also inject this custom implementation.

**Comment by jbogard** [comment]
If it’s for testing can’t you already replace the implementation in the
service collection? You can remove one item and add another straight on
that object?

**Comment by thiagolunardi** [comment]
As I said, really doesn't matter what anyone custom implementation does, what is being asked is for an option for, if I have my own then I'd like to register it instead of the default one using this nice extension.

Adding more info - as I have it just now - I customized it to do some logs, using `X-HttpRequest-Id` and adding it as a `Singleton`  when I'm using it in a non-web Host.

**Comment by jbogard** [comment]
Are you prevented from registering a custom one today?

**Comment by thiagolunardi** [comment]
Using this extension as is, it's not possible.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by jbogard** [comment]
Oh I found a built-in way:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.extensions.servicecollectiondescriptorextensions.replace

We don’t need anything custom, you can already remove and replace any
registration.

TIL

**Comment by thiagolunardi** [comment]
Ok, I was already using like that, but I was expecting something else. Anyhow, thanks for your time, and great job! I'm having a nice case of use here. If you someday be interested to know, just ping me. :+1:
