### ISSUE TITLE
Help Required

### ISSUE THREAD

**Issue by abomadi** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#50]
Im trying to use MediatR across multiple class libraries as the following :

```
- Project 1 >> Raise INotification<EventTest>
- Project 2 >> Handle INotificationHandler<EventTest>
- Project 3 >> Handle INotificationHandler<EventTest>
```

if i create handler withing the same class library it works well, however Project 2 and 3 handlers are never triggered, i register all the above using Microsoft DI and Scrutor
any help plz ?

**Comment by jbogard** [comment]
You shouldn't need to register notification handlers, `AddMediatR` does that already.
