### ISSUE TITLE
Release 5.2.0?

### ISSUE THREAD

**Issue by dennisroche** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#54]
Any reason why `5.2.0` has been delayed?

The version was bumped in this PR https://github.com/jbogard/MediatR.Extensions.Microsoft.DependencyInjection/pull/53 25 days ago.

**Comment by jbogard** [comment]
Spite?

**Comment by dennisroche** [comment]
Figured as much.

**Comment by jbogard** [comment]
Lol honestly I forgot. There was another PR with a breaking API change so I
wanted to wait to see what came out of it.

**Comment by dennisroche** [comment]
No problem. It did take 20 minutes to realize why the documentation didn't match the `nuget` package. 

Release when you're ready... I've copied the source locally so that I can continue.

**Comment by jbogard** [comment]
Released!
