### ISSUE TITLE
What's the right way to register IPipelineBehavior

### ISSUE THREAD

**Issue by VincentSCW** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#57]
Hi,

I have a PipelineBehavior like below
` public class TracingBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
    {
        public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
        {
            throw new NotImplementedException();
        }
    }`

Then I only add `services.AddMediatR()` into Startup.cs. But it doesn't work.
So I tried to inject it manually, like
`services.AddScoped(typeof(IPipelineBehavior<,>), typeof(TracingBehavior<,>));`
But it still doesn't work...

May I know what is the right way to register it?

Thanks.

**Comment by VincentSCW** [comment]
So, do you mean below is right?
`services.AddScoped(typeof(IPipelineBehavior<,>), typeof(TracingBehavior<,>));`

Actually I don't see it works, nothing happens at all... I want it be hit for each http call.

**Comment by jbogard** [comment]
Yeah, that's correct. To debug, I'd first examine the registrations in the container. Make sure everything you expect to be registered, is registered.

Next, try resolving the dependencies, starting from the inner-most to the outer-most. Try just resolving a closed behavior type, then enumerable of behaviors for a closed `IEnumerable<IPipelineBehavior<,>>` etc.
