### ISSUE TITLE
Make ServiceCollectionExtensions.AddMediatRClasses public

### ISSUE THREAD

**Issue by BalassaMarton** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#60]
Use case: message handlers are in different projects (plugins), each having its own AddXXX method for single line configuration in the hosting project. The hosting project will not pass any assembly references to MediatR, as plugin registration is separated from infrastructure setup.

**Comment by jbogard** [comment]
How is the hosting project calling the configuration for the plugins? They all have to use the same service collection, right?

**Comment by BalassaMarton** [comment]
Yes, each plugin has an `AddXXX(this IServiceCollection)` method, the host just composes the application by calling these registration methods, and then the plugins register their application parts and message handlers in the collection. Not that I can't write the same utility method (or copy it), but making the original public looks like a one-liner.

**Comment by jbogard** [comment]
I don't really want to expand the public API in the root namespace. However, I'd be open to moving that assembly scanning stuff outside to a sub-namespace and making it public.
