### ISSUE TITLE
Sign "MediatR.Extensions.Microsoft.DependencyInjection" assembly

### ISSUE THREAD

**Issue by sanhomealex** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#62]
It is better to have "MediatR.Extensions.Microsoft.DependencyInjection" signed in order to exclude warnings when it is referenced in signed assemblies, for example:

`CSC : warning CS8002: Referenced assembly 'MediatR.Extensions.Microsoft.DependencyInjection, Version=6.0.1.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

**Comment by jbogard** [comment]
Whoops, oversight on my part.

**Comment by sanhomealex** [comment]
No problem, this is not a case for those who have cloned the repo, however for one who is using NuGet package the warning might sometimes be annoying :-)
