### ISSUE TITLE
Mediatr don't know publish to singleton registrations for INotificationHandler<T>

### ISSUE THREAD

**Issue by bulpet** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#63]
When we use singleton service for handle INotificationHandler<T>, mediatr.publish(T)  method make new instance of service every publish.

Its not good behaviors,  we need make only one instance (singleton) of our service. but currently we can't do it because we use mediatr, and mediatr don't know how to publish message to singleton 

Please fix this issue ASAP

**Comment by lilasquared** [comment]
Why does the Notification handler need to be a singleton?  The notification handler can depend on a singleton service which it offloads the work to.

**Comment by jbogard** [comment]
Yes, don't register handlers as singleton. Those should be transient.
