### ISSUE TITLE
Possible bug closing open concrete types

### ISSUE THREAD

**Issue by michielrutting** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#8]
I was trying to figure out what use case is adressed by the following section of code in the AddMediatRClasses method:
```
if (!@interface.IsOpenGeneric())
{
    AddConcretionsThatCouldBeClosed(@interface, concretions, services);
}
```
I think it's supposed to try and close open generic concrete classes (like an open generic handler?) for every closed handler interface that was found. I wasn't able to find anything in the tests that resulted in the AddConcretionsThatCouldBeClosed method actually trying to add a registration. 

I'm not sure it will ever try to do so as the CouldCloseTo method compares the number of generic type arguments of the closed type to the number of generic type arguments of the open type. Shouldn't it be comparing those to the number of generic type **parameters**? To get that the line above should I think be:
```
var concreteArguments = openConcretion.GetGenericArguments();
```
instead of:
```
var concreteArguments = openConcretion.GenericTypeArguments;
```
See http://stackoverflow.com/questions/19503905/type-generictypearguments-property-vs-type-getgenericarguments-method

It could be I'm reading this all wrong though, sometimes reflection does my head in :)

**Comment by jbogard** [comment]
Do you have a test that fails that I could verify? This code I copied from StructureMap.
