### ISSUE TITLE
Control the order of execution of IRequestPostProcessor implementations

### ISSUE THREAD

**Issue by jstevense-vbe** [jbogard/MediatR.Extensions.Microsoft.DependencyInjection#92]
I have a pipelinebehavior with 2 IRequestPostProcessor implementations. The order in which they execute seems to be alphabetic which in my case is accidentically correct. :)

Is there a way to control the order of execution? Or do I have to reside to not using this extension and register all by myself?

Thank you for this great library!

**Comment by jbogard** [comment]
The container controls the order HOWEVER I would not rely on this necessarily. If there is something where one has to execute before the other, then compose these two actions in a single processor.

**Comment by jstevense-vbe** [comment]
Good point, thank you for your fast reply.
